### PR TITLE
Fix offsettop for scrollto functionality

### LINKED ISSUE #1711: Scrollto padding
A bit broken

### PR DESCRIPTION
**Pull request by RonaldDijkstra**
Fix #1711 

This took the height of `.header`, but `.header` doesnt exist anymore. 

Probably want Javascript tests... 🤔

### CODE REVIEW

File: source/javascripts/_scroll-to.js [hunk 1]
```diff
@@ -1,11 +1,11 @@
 $(function() {
   "use strict";
 
-  var offsetTop = -$(".header").height();
+  var offsetTop = -$(".global-navigation").height();
```
Comment (sn3p) [inline source/javascripts/_scroll-to.js]:
```suggestion
  var offsetTop = -$(".global-navigation").height() * 1.5;
```
